
version: 1.0.{build}
build:
  verbosity: minimal
  project: Project.sln


configuration: Release


environment:
  QTDIR: 'C:\projects\lilypondsvgwidget\qt-5.6.0-static'

install:
  - curl.exe -s -o qt-5.6.0-static-msvc2015_x86.zip http://familiekainz.at/libs/qt-5.6.0-static-msvc2015_x86.zip
  - 7z x qt-5.6.0-static-msvc2015_x86.zip

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - set CMAKE_PREFIX_PATH=%QTDIR%;%CMAKE_PREFIX_PATH%
  - cmake -G "Visual Studio 14 2015" -DQT5_STATIC_LIBS=C:\projects\lilypondsvgwidget\qt-5.6.0-static\lib\qtharfbuzzng.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\lib\qtfreetype.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\lib\qtpcre.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\lib\Qt5PlatformSupport.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\plugins\platforms\qminimal.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\plugins\platforms\qoffscreen.lib;C:\projects\lilypondsvgwidget\qt-5.6.0-static\plugins\platforms\qwindows.lib;imm32.lib;winmm.lib;Ws2_32.lib;iphlpapi.lib .
#  - cmake --build . --config Release
  - dir


build_script:
  - msbuild Project.sln /p:Configuration=Release
  - msbuild PACKAGE.vcxproj /p:Configuration=Release


artifacts:
  - path: Project-0.1.0-win32.exe
  